### ISSUE TITLE
Registration - Unexpected output when a not found email is used.

### ISSUE THREAD

**Issue by dilinipeirs** [bitsoferised/ShareABook_Frontend_v.2#1]
Since you changed the data to be sent to the server the registration actually did not work in the backend, because according to how it was earlier, i have put to return a boolean value if the registration was successful...
![image](https://user-images.githubusercontent.com/28673959/78929061-59134a00-7abf-11ea-80d4-843868f74ee1.png)
so what you are printing here are the data that are there in the registration form. and you are setting these data into the local storage.. 

i have adjusted the code to send you user details as a json if the registration was successful...
what you actually have to do now is, you have to check this response first.. if **it is null**-> **you cannot let the user go to the dashboard..**
if it is **not null only** you have to set **this json** into the **local storage** and let the user go to the dashboard.

Previously you weren't actually checking if the registration was successful..

u-register.component.ts
![image](https://user-images.githubusercontent.com/28673959/78929693-785ea700-7ac0-11ea-9c33-6c022045b96b.png)

**Comment by dilinipeirs** [comment]
As we discussed the other day, we are not letting the user go to the dashboard if the registration was successful.
Therefore please do the following changes;

1. im returning a boolean if the registration was successful
   if true -> display message - u were registered successfully, please check your emails and follow the steps to verify your email address.
meanwhile, direct him to the log in screen

if false - error in registering to the system etc.

**Comment by dilinipeirs** [comment]
Kanishka sir said to take the email address as the username.
Therefore, remove the username field.

And also, add a city field to the registration form, apart from the address, we need the city as well, for payment and delivery purposes..
And also put first name and last name separately, we need them for payment module

![image](https://user-images.githubusercontent.com/28673959/79220317-63dc2f00-7e71-11ea-9b91-021b3524d38c.png)

**Comment by Nethmi96** [comment]
As per the above mentioned requirements I've done the necessary changes to the registration form. But it can be seen even at a situation where I've entered an invalid/ **not found** email address still the form is working fine, also the returned value from the backend is **true**. Refer the image below for more details. In the console I've printed the data entered in the registration form and the returned value from the backend (which is true).

![image](https://user-images.githubusercontent.com/44530828/79270381-b0e4f300-7ebb-11ea-9c6e-2434094b08d8.png)

**Comment by dilinipeirs** [comment]
As of now, this seems out of my hands.. Im looking into it. I will resolve this as soon as i get to know something.

**Comment by Nethmi96** [comment]
Okay 👍

**Comment by dilinipeirs** [comment]
in the gmail itself, we can send emails to a wrong email address and it gives a delivery fail msg.. 

have to research on this a bit more
