### ISSUE TITLE
Maintain a constants file in the frontend

### ISSUE THREAD

**Issue by dilinipeirs** [bitsoferised/ShareABook_Frontend_v.2#10]
When you are declaring the URLs for the API endpoints in the frontend, the part 'http://localhost:8080/shareabook/api/v1/' is going to be same for all the URLs. Therefore, declare this as a constant in your project and use it everywhere you have to call an endpoint. 

Use string concatination to create the final URL.

Because when we host this, the URL changes and everytime there is a version change you have to edit the URL in each and every file.

So follow this best practice from the start

**Comment by Nethmi96** [comment]
Helper service is added
