### ISSUE TITLE
Forgot Password option should be added to the login page

### ISSUE THREAD

**Issue by dilinipeirs** [bitsoferised/ShareABook_Frontend_v.2#11]
Please add the forgot password option as follows..

Note that, now no username, we are asking only for the email now. Therefore please rename the username/email field to **Email address**

![image](https://user-images.githubusercontent.com/28673959/79349928-754a3780-7f54-11ea-8ce4-a6619303f90f.png)

url: http://localhost:8080/shareabook/api/v1/authentication/forgot
please send the email address as a request parameter.

response: im sending a boolean from the backend. Therefore display alert msgs accordingly.

- true -> Your password was reset successfully. Please check your emails and follow the steps provided
- false -> Error in resetting your password. Please contact support

**Comment by RashmiChrystal** [comment]
This is done and is committed to the branch named "forgot_password"
