### ISSUE TITLE
Add Book

### ISSUE THREAD

**Issue by Nethmee** [bitsoferised/ShareABook_Frontend_v.2#116]
in the add  book form when I first selected A/L as the sub category then then sub category 2 and 3 comes as expected and then when I change sub  category into O/L there is still the sub category 3 field  with previous results .
<img width="589" alt="add book bug" src="https://user-images.githubusercontent.com/40081010/90162712-af1c3500-ddb2-11ea-8e3a-2b8d6606ec9e.PNG">

**Comment by dilinipeirs** [comment]
@Nethmi96 please look into this together with the new Add book form features
