### ISSUE TITLE
retrieving book data from the backend

### ISSUE THREAD

**Issue by dilinipeirs** [bitsoferised/ShareABook_Frontend_v.2#12]
i have included quality, category and book location to the book json.. 
since there is a lot of data to be sent, the category details are sent as a another object inside the book object.

following are the structures of the java classes

1. book object class
![image](https://user-images.githubusercontent.com/28673959/79498800-8162f180-8047-11ea-91c1-8d7e27aa6900.png)

please read and follow the comments in the above picture.

please hard code the **highlighted ones** to the frontend as they are not that important to be managed by the admin. **But make sure to use the exact spellings as i have mentioned in the pic**

2. the category object class is as follows
![image](https://user-images.githubusercontent.com/28673959/79499297-5c22b300-8048-11ea-9767-ae574fd09e05.png)

the commented ones are how i am saving data in the database.
the highlighted ones may not look nice to be shown directly in the frontend. Therefore, when i send the data from the backend, check whether they are these and display the text nicely in the frontend
eg: 
- **STUDY_MATERIAL** from backend can be shown as **Study Material** in the frontend
- **AL** from backend can be shown as **Advanced Level** in frontend

**Comment by Nethmi96** [comment]
Okaay.
Thanks :-)

**Comment by dilinipeirs** [comment]
please refer the new object structures of book and category as follows

book
![image](https://user-images.githubusercontent.com/28673959/79748578-502a4000-832b-11ea-8e94-91034755142a.png)


category
![image](https://user-images.githubusercontent.com/28673959/79748618-5cae9880-832b-11ea-84d6-bb10d43ddaa1.png)
