### ISSUE TITLE
Profile Update Error

### ISSUE THREAD

**Issue by Nethmi96** [bitsoferised/ShareABook_Frontend_v.2#16]
I'm getting a status code 500 error when trying to update user profile
![image](https://user-images.githubusercontent.com/44530828/79639625-91dfad00-81aa-11ea-8767-9832a738cd29.png)

**Comment by dilinipeirs** [comment]
this error you mentioned is resolved.

But i am getting another error in the frontend...
in the backend the user details are sent and there is no error in the backend..
Please check if you can do something regarding this error

![image](https://user-images.githubusercontent.com/28673959/79669466-48f31d00-81d9-11ea-852a-b49ba6f8deda.png)

**Comment by Nethmi96** [comment]
Solved!
