### ISSUE TITLE
Create Manage Feedbacks component in the admin dashboard

### ISSUE THREAD

**Issue by Nethmi96** [bitsoferised/ShareABook_Frontend_v.2#17]
Create the manage feedback component in the admin dashboard according to following functions adn UI.
![image](https://user-images.githubusercontent.com/44530828/79700426-1c133880-82b3-11ea-8680-18d8d95651e7.png)

You can just copy paste the UI of manage-users component in admin panel and import manage-users css file to the manage-feedback css file.

When creating the feedback table you may need to follow angular material table: https://material.angular.io/components/table/examples
and manage-user.component.ts file.

Happy Coding :)

**Comment by dilinipeirs** [comment]
all feedback related endpoints are now done in the backend. (Refer the API doc)

please find the changes in the feedback UI as follows.

![image](https://user-images.githubusercontent.com/28673959/80118600-42ccba00-85a6-11ea-967a-e448a17880a5.png)

**Comment by dilinipeirs** [comment]
@RashmiChrystal please close this issue after the error in manage feedback are resolved

**Comment by RashmiChrystal** [comment]
All done. A few changes to the feedback component was done and committed to the branch named issues
