### ISSUE TITLE
Error in adding new admin

### ISSUE THREAD

**Issue by Nethmi96** [bitsoferised/ShareABook_Frontend_v.2#19]
Hiiii diliniiiiiiiiiii :)

When I'm trying to add a new admin to the platorm eventhough i get the response from the backend as true and received an email, an **error occures when I'm trying to confirm the email received.**
![image](https://user-images.githubusercontent.com/44530828/79861234-b5486900-83f1-11ea-94d9-df88f205440f.png)
![image](https://user-images.githubusercontent.com/44530828/79861256-ba0d1d00-83f1-11ea-814f-222aba8fe8ca.png)

Also, after trying to add a new admin due to the error occurred now I cannot get any admins or students registered in the platform.
![image](https://user-images.githubusercontent.com/44530828/79861390-f80a4100-83f1-11ea-8a01-e690fee663c3.png)

Console error is attached here.
![image](https://user-images.githubusercontent.com/44530828/79861433-03f60300-83f2-11ea-8f1c-918fadc62ec0.png)
![image](https://user-images.githubusercontent.com/44530828/79861448-0b1d1100-83f2-11ea-9088-be4264ec5ea4.png)
![image](https://user-images.githubusercontent.com/44530828/79861469-12441f00-83f2-11ea-949c-bfe0afae9393.png)
![image](https://user-images.githubusercontent.com/44530828/79861484-196b2d00-83f2-11ea-8214-a2c427a84f0f.png)
![image](https://user-images.githubusercontent.com/44530828/79861501-20923b00-83f2-11ea-9e88-31396128385d.png)
![image](https://user-images.githubusercontent.com/44530828/79861517-27b94900-83f2-11ea-8a80-c52c247fe06f.png)

**Comment by dilinipeirs** [comment]
XO

all of this is working fine now.. 😷🤤

**Comment by Nethmi96** [comment]
When I'm trying to load all admin details an error occurs
![image](https://user-images.githubusercontent.com/44530828/80208319-93e3b900-864d-11ea-9c53-588ca1aa20a2.png)

**Comment by dilinipeirs** [comment]
Please take a pull from the backend and see. This error is already resolved earlier
