### ISSUE TITLE
Add Book - Bug

### ISSUE THREAD

**Issue by dilinipeirs** [bitsoferised/ShareABook_Frontend_v.2#2]
If you saved the user data from the backend into the local storage, technically this problem should be solved..
If it was not yet solved even after the issue in registration was done, open a new issue assigning me

**Comment by Nethmi96** [comment]
Done and dusted

**Comment by dilinipeirs** [comment]
in the new add book form, when i click on the Add Book button at the end, the request doesnt come to backend. Please look into this

**Comment by dilinipeirs** [comment]
Please try adding these book details
![image](https://user-images.githubusercontent.com/28673959/82093288-78357500-9718-11ea-94f8-1fec82f5908c.png)

when i try to add these details, the request doesnt come to the backend and that red colour Add book failed alert comes =(

**Comment by Nethmi96** [comment]
It is working fine in mine 
![image](https://user-images.githubusercontent.com/44530828/82138979-520bf400-9842-11ea-8efe-a226dfdc1409.png)

**Comment by Nethmi96** [comment]
It is working fine in mine
![image](https://user-images.githubusercontent.com/44530828/82138997-88497380-9842-11ea-8a9a-4e7f08c8d323.png)

**Comment by dilinipeirs** [comment]
**this bug is still there in mine.. please check whether you have committed all the files successfully.** 

and there are a few more bugs in this process..

1. since adding O/L level books does not send the request to the backend in mine, i tried going back i the form by clicking on the tabs and changed the product type to story book as follows..

![image](https://user-images.githubusercontent.com/28673959/82141957-707bea80-9856-11ea-9187-6775eced96af.png)

as u can see in the above pic, the product type is changed but the subCat details are still as earlier.. please look into this

2. the above category details are invalid. because story books dont have sub categories as ordinary level. Therefore the book does not get add to the database and returns -1 since it is unsuccessful.

![image](https://user-images.githubusercontent.com/28673959/82142015-00ba2f80-9857-11ea-9a3e-8a2877a47708.png)

the book adding was unsuccessful and sends -1 as the book id. When this happens the **image adding pop up should not be shown**.

**Comment by Nethmi96** [comment]
I have adjusted the above mentioned bugs, but still couldn't find why add the previously mentioned issue is not working in yours properly. Please take a pull from the front end and see...In the meantime I'll look what i can do for that

**Comment by dilinipeirs** [comment]
![image](https://user-images.githubusercontent.com/28673959/82151996-29a0eb80-987c-11ea-8cc2-aef71b2ae286.png)

another small issue. here when i select grade 6-9, the sub cat 3 field is displayed. please look into this

**Comment by dilinipeirs** [comment]
the previous error is now resolved 😁. 

do look into the grade 6-9 error

**Comment by Nethmi96** [comment]
Resolved!
