### ISSUE TITLE
Error in book editing 

### ISSUE THREAD

**Issue by Nethmi96** [bitsoferised/ShareABook_Frontend_v.2#20]
Issue in the frontend is solved. But now when i'm trying to edit a book i am getting a server error.
![image](https://user-images.githubusercontent.com/44530828/80301422-ab43b300-87c1-11ea-98f3-fd340a8a8ee4.png)

Error in the console:
![image](https://user-images.githubusercontent.com/44530828/80301433-b991cf00-87c1-11ea-8eed-1316f743b88c.png)

**Comment by dilinipeirs** [comment]
this is now resolved i believe?
