### ISSUE TITLE
implement notifications in frontend

### ISSUE THREAD

**Issue by dilinipeirs** [bitsoferised/ShareABook_Frontend_v.2#22]
the list for now:
![image](https://user-images.githubusercontent.com/28673959/80828107-5dd0a700-8c02-11ea-8b31-f545a82691b9.png)

this will be updated when any other situations are identified.

inform dilini on what needs to be done on the backend regarding this

**Comment by dilinipeirs** [comment]
the following will be the process of notifications in the system

for @Nethmee and @RashmiChrystal 's reference

![image](https://user-images.githubusercontent.com/28673959/83326317-b8f0ca80-a290-11ea-8819-bbf66b1abf8f.png)

**Comment by dilinipeirs** [comment]
https://stackoverflow.com/questions/53403792/can-i-use-firebase-cloud-messaging-without-notification-permission-javascript according to this, we cannot opt out from showing the request for notification pop up.

firebase only lets us (the app) to notify users if the users are comfortable with it.. so if a user clicks on block (which can highly happen), our objective is not fulfilled..

Therefore, according to the discussion @Nethmee and i had, we will be handling the notifications like any other request from frontend to backend..

then the notification sending and storing part will happen from the backend.. therefore, the frontend will be given just one endpoint to retrieve the notifications for a specific user.. (this endpoint is to be called several times in the frontend to make sure that notifications are refreshed.)

the endpoint can be called
- upon clicking on the notification icon
- on each page load

Therefore, @RashmiChrystal please provide your views on this. Then I can implement the backend endpoint asap. From the frontend, you will have to manage the UI to show the notifications to the user.. (like the notifications component in medium, or a seperate page for notifications.. -> my personal opinion is the component like in medium is better bcz this is just a ecommerce site)

**Comment by RashmiChrystal** [comment]
Okay this way is faster. Also, I agree with displaying the notification pane as that in Medium. We can do it this way then. I'll write the code in the frontend for this.

**Comment by dilinipeirs** [comment]
Okay great!

**Comment by dilinipeirs** [comment]
the endpoints for this feature are made. please refer 'Notification Related' in the API doc

the following are the scenarios where notifications are being sent
![image](https://user-images.githubusercontent.com/28673959/83780610-07e09a80-a6ab-11ea-855d-de30f5c255fe.png)

@Nethmee please test the backend using postman for the endpoints for this feature. 
But in order for notifications to be saved, first you will have to follow the scenarios in the above picture, so that notifications will be saved for specific users in the database. After that, you can use the endpoints to check them.

@Nethmee Please report any backend errors under the backend repo as new issues.

@RashmiChrystal you can integrate the frontend by using the endpoints given

**Comment by RashmiChrystal** [comment]
@dilinipeirs could you go through the photo i have attached here. I have mapped the situations you have mentioned above to the respective pages they need to be routed to. The question marks indicate doubts and it would be great if you could clarify.

![issue1](https://user-images.githubusercontent.com/45396207/83896686-2b224d00-a772-11ea-903f-b70d7f929ef4.jpg)

**Comment by RashmiChrystal** [comment]
> @dilinipeirs could you go through the photo i have attached here. I have mapped the situations you have mentioned above to the respective pages they need to be routed to. The question marks indicate doubts and it would be great if you could clarify.
> 
> ![issue1](https://user-images.githubusercontent.com/45396207/83896686-2b224d00-a772-11ea-903f-b70d7f929ef4.jpg)
> 
> Also note that i route the notifications by considering the notification type. So all notifications of a certain type will have to be routed to the same destination.
> 
> Another clarification => are those the only 3 notification types that are sent from the backend and are the spelling correct? (cause these should be hard coded)

**Correction**
the 4th situation is A not B.

**Comment by dilinipeirs** [comment]
@RashmiChrystal 

![image](https://user-images.githubusercontent.com/28673959/83902765-9ff98500-a77a-11ea-88a2-9452e5310eec.png)

spellings are as above

**Comment by dilinipeirs** [comment]
> @RashmiChrystal
> 
> ![image](https://user-images.githubusercontent.com/28673959/83902765-9ff98500-a77a-11ea-88a2-9452e5310eec.png)
> 
> spellings are as above

@RashmiChrystal as far as i am aware of, there are enums in angular as well.. so you dont need to hardcode any types that i am sending from the backend

**Comment by RashmiChrystal** [comment]
Notifications are complete and committed to new-notifications branch. And a pull requests was created. @Nethmi96
