### ISSUE TITLE
Login - functionality changed

### ISSUE THREAD

**Issue by dilinipeirs** [bitsoferised/ShareABook_Frontend_v.2#3]
I checked the backend using postman and it is working fine..
When sending the request from frontend, im getting the username password as **null** values.. therefore please look into it.. 

run it with the backend together..
register a user and then try logging in

**Comment by dilinipeirs** [comment]
rashmi you havent done null validation in the frontend. check here
![image](https://user-images.githubusercontent.com/28673959/79041589-99cda900-7c0e-11ea-9859-37536dd1ac98.png)

if the password or username entered is incorrect, the backend sends a null value.. therefore, you have to check whether the response is null first. 
if it is null, then you have to give an alert saying, 'check username and password again' or something..
If it not null, then it means the details are correct and the backend is sending the specific users user details as the response. Then u have to save **this response** to the local storage. check how nethmi has done the registration code.. there she catches the response and saves it to local storage

**Comment by dilinipeirs** [comment]
Rashmi please check this **again** by clearing the local storage and logging in again..
i think there is something wrong and the username is not shown in the dashboard
![image](https://user-images.githubusercontent.com/28673959/79048731-c13b6a80-7c3c-11ea-946b-693b9129ee8e.png)

the details are coming from the backend.. but there is an error
![image](https://user-images.githubusercontent.com/28673959/79048746-da441b80-7c3c-11ea-922e-2bc60d38a320.png)

**Comment by dilinipeirs** [comment]
Rashmi as we discussed that day, the login should be permitted only if all the following conditions are met. 

1. the email address should be already verified by the user
2. the user's account should not been banned by the admin
3. the username password should be valid (only this is checked as of now)

Therefore, in order to cater these changes, i am in the process of making changes in the backend (not finished yet).
Therefore, till i finish the backend, please do these changes to the frontend so that those changes can be adapted.

when u send the POST request to the backend for login, i am sending the following object's JSON as the response.
![image](https://user-images.githubusercontent.com/28673959/79157306-02c14680-7df2-11ea-9ab8-c92b2792005f.png)

This contains if the login was successful (boolean)
if true -> login was successful. Then the user details will be there in the attribute **ifSuccessUser**, so you have to take this user json and save it to the local storage as u did earlier.
if false -> i will be sending you the reason in the String attribute **ifFailedReason**. Then you have to get this string and **show it in a dialog box/pop up window something**.

> possible reasons for login failing
a. the username/password is incorrect
b. the user haven't verified his email. -> here after displaying the message i am sending in the dialog box, please put a link saying 'Resend Email verification link' and put the URL as http://localhost:8080/shareabook/api/v1/authentication/resend and send me the username he typed in as a request parameter. So then i will be sending an email from the backend.
c. user is banned. Here i will be sending the relevant msg. Put a link here as **For more details: Contact Support** and direct him to the support page.

**Comment by Nethmi96** [comment]
In this I want to clarify whether that the **failureType** is an attribute which comes under **ifFailedReason**.

I'll take it as that and do the necessary changes to the frontend and commit. Inform if any changes need to be done.

**Comment by dilinipeirs** [comment]
![image](https://user-images.githubusercontent.com/28673959/79347266-159e5d00-7f51-11ea-9741-e7a86f79acdc.png)

Nethmi here you havent done the steps i have said neda? you are just putting the result into the local storage as earlier ne

**Comment by Nethmi96** [comment]
I haven't finish login yet xD 
This is the previous login donne by Rashmi.
I'll finish it and commit tonight

**Comment by dilinipeirs** [comment]
I thought you closed it because you finished it XD

refer the diagram, this shows the flow of events in login

the red color circled ones are messages that are sent to by the backend. So you just have to display accordingly after identifying the failure type.

![image](https://user-images.githubusercontent.com/28673959/79351842-ca874880-7f56-11ea-945c-577529c88b56.png)

url for resend verification: http://localhost:8080/shareabook/api/v1/authentication/resend
response - a boolean is sent
true -> ask to check emails and follow instructions
false -> resend verification failed. ask to contact support

**Comment by Nethmi96** [comment]
Dilini as you mentioned i've done the particular changes to the login frontend. 
1. According to your diagram for a user who have **not registered** to the platform the error which should be displayed is **"Sign up to Share a Book"** or something like that right? But what I'm getting is the same error when there is a mismatch in the username and password. Please refer to the image below.
![image](https://user-images.githubusercontent.com/44530828/79421487-82a90580-7fd8-11ea-98e7-02b850f5c1a9.png)

2. 2nd option you mention **(the user haven't verified his email.)** is still not working. @RashmiChrystal please look into that. You have to send the value of the email in the login form to the backend. I put a comment above the code of that part in the login.component.ts

![image](https://user-images.githubusercontent.com/44530828/79421706-ff3be400-7fd8-11ea-8f53-677df6ff8468.png)

3. @dilinipeirs As I've checked we cannot put links in alerts. Therefore,  can you please change the message in the following situation to => **You have not verified your email address. Please check your inbox for new verification link** or something like that? 

![image](https://user-images.githubusercontent.com/44530828/79421849-52ae3200-7fd9-11ea-8d46-c66a53c9a80a.png)

**Comment by dilinipeirs** [comment]
1 and 3 Done

**Comment by RashmiChrystal** [comment]
2 is working. i'll commit it to the branch named 'rashmi'
