### ISSUE TITLE
Bind number of items in the cart to the badge in the header

### ISSUE THREAD

**Issue by Nethmi96** [bitsoferised/ShareABook_Frontend_v.2#34]
Number displayed in the shopping cart badge should be change according to the number of items in the shopping cart.
Also, if there are no items in the cart this badge should be hidden.
![image](https://user-images.githubusercontent.com/44530828/81098174-9d5f0200-8f26-11ea-899c-f1bbd549c263.png)

Refer the following documentation for more details.
https://material.angular.io/components/badge/overview

**Comment by RashmiChrystal** [comment]
done and committed to the branch named "issues"
