### ISSUE TITLE
Add Item to the cart when "Shopping cart" icon in the dashboard product card clicked

### ISSUE THREAD

**Issue by Nethmi96** [bitsoferised/ShareABook_Frontend_v.2#35]
Add Item to the cart when "Shopping cart" icon in the **dashboard product card** clicked
![image](https://user-images.githubusercontent.com/44530828/81142259-c619e280-8f8c-11ea-95aa-5618ef5fb56a.png)

**Comment by RashmiChrystal** [comment]
done and committed to the branch named issues
