### ISSUE TITLE
Encrypt Book Id

### ISSUE THREAD

**Issue by Nethmi96** [bitsoferised/ShareABook_Frontend_v.2#41]

**Comment by dilinipeirs** [comment]
this is not required as it not a huge security breach =D

**Comment by dilinipeirs** [comment]
![image](https://user-images.githubusercontent.com/28673959/82093643-26411f00-9719-11ea-80d5-99d5789f541b.png)

look into this error

changes done - the public id was inserted to the frontend code in several lines.. tried removing those lines and putting the key in one line -> still did not work

**Comment by dilinipeirs** [comment]
this was paused as couldnt achieve the task
