### ISSUE TITLE
Issue in blocking a book by admin

### ISSUE THREAD

**Issue by Nethmi96** [bitsoferised/ShareABook_Frontend_v.2#46]
I am getting an issue when try to block a book by an admin
![image](https://user-images.githubusercontent.com/44530828/82090767-ceec8000-9713-11ea-84db-81ae2bbd357b.png)

Console error is as follows
![image](https://user-images.githubusercontent.com/44530828/82090825-ea578b00-9713-11ea-9534-1794d7c6c43e.png)

**Comment by dilinipeirs** [comment]
Please show me the frontend code on how you are sending the data in the request body

**Comment by Nethmi96** [comment]
bookDto is sending in the **other** field.
![image](https://user-images.githubusercontent.com/44530828/82137692-f2a8e680-9837-11ea-8dfe-1894bd82ee21.png)

**Comment by dilinipeirs** [comment]
This is resolved. 

tested from both postman and frontend.
