### ISSUE TITLE
Issue in delete a category

### ISSUE THREAD

**Issue by Nethmi96** [bitsoferised/ShareABook_Frontend_v.2#47]
Console error
![image](https://user-images.githubusercontent.com/44530828/82148543-4c2e0700-9872-11ea-9d6e-b984c22ce485.png)
![image](https://user-images.githubusercontent.com/44530828/82148573-57813280-9872-11ea-830f-d882db16eed9.png)
![image](https://user-images.githubusercontent.com/44530828/82148612-5ea84080-9872-11ea-97d2-ce5b0ffd816d.png)

Console error in front
![image](https://user-images.githubusercontent.com/44530828/82148794-84354a00-9872-11ea-942e-4917dbf8f301.png)

Also, when i checked this in postman even for a category where there are no books listed under it => response is displayed as **false**
![image](https://user-images.githubusercontent.com/44530828/82148907-b777d900-9872-11ea-94f5-07391b6548de.png)

**Comment by dilinipeirs** [comment]
the error you have shown somehow did not occur in mine.

there was a small bug that prevented the book from deleting.. and i corrected it. It should fine now.

try deleting from the postman first and see. Then use in the frontend.

I've changed the request type to **DELETE** as u suggested. It did work with POST too after correcting the error.. but changed it anyway 😂
