### ISSUE TITLE
Sign up form -UI

### ISSUE THREAD

**Issue by Nethmee** [bitsoferised/ShareABook_Frontend_v.2#57]
background-color of some fields are  bit different than the rest.

**Comment by Nethmi96** [comment]
Can you be more specific on what did you mean by **'some fields'**? Cz i cant see any difference 😄

**Comment by Nethmee** [comment]
> Can you be more specific on what did you mean by **'some fields'**? Cz i cant see any difference 😄
> @Nethmee

![registration](https://user-images.githubusercontent.com/40081010/82763432-55484680-9e25-11ea-9e61-831b0c708cc1.PNG)

**Comment by Nethmi96** [comment]
Ah no. This is not happening in some fields. If the user select a value which is saved in his history, for an example like in the image below that value gets highlighted or something.
![image](https://user-images.githubusercontent.com/44530828/82763733-61350800-9e27-11ea-8120-3c66772a5c41.png)

I tried different method to override this but didn't get succeed.
Therefore, this is issue is paused for now.
