### ISSUE TITLE
Password match-registration form

### ISSUE THREAD

**Issue by Nethmee** [bitsoferised/ShareABook_Frontend_v.2#58]
![passsword match](https://user-images.githubusercontent.com/40081010/82763803-d56fab80-9e27-11ea-922f-9809b8a456f5.PNG)
As of now if the password length is less than 8 , the error message being displayed is "require a password".It will be better if we can give more specific error messages for the corresponding scenario.

**Comment by Nethmi96** [comment]
This one is already completed. Take a push and check
