### ISSUE TITLE
Price of a material displays as 0.

### ISSUE THREAD

**Issue by Nethmi96** [bitsoferised/ShareABook_Frontend_v.2#6]
![image](https://user-images.githubusercontent.com/44530828/79043482-110a3980-7c1d-11ea-94bb-23f7d2ff7979.png)
All the details are displaying correctly except for the price of the material. Price of a the material always comes as 0, not only for the books added recently, but also for the books which was added previously same error occurs.
![image](https://user-images.githubusercontent.com/44530828/79043571-8aa22780-7c1d-11ea-9b79-81a5aa0bf784.png)

I can remember that the same error occurred during competition days and you've done something to resolve it.

**Comment by dilinipeirs** [comment]
yes there are some changes that needs to be done to the ER. Therefore i will look into this tomorrow
