### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by Nethmee** [bitsoferised/ShareABook_Frontend_v.2#63]
get an error of status code 500 after entering the email.

**Comment by dilinipeirs** [comment]
please provide the email you entered

**Comment by Nethmee** [comment]
> please provide the email you entered

It's  "nssellahewa@gmail.com"

**Comment by Nethmi96** [comment]
I also tried with my email.
This is the console error i got
![image](https://user-images.githubusercontent.com/44530828/83050526-574f1700-a06a-11ea-8337-941f69a75b97.png)

**Comment by dilinipeirs** [comment]
this error is resolved

@Nethmee please check now
