### ISSUE TITLE
Manage donations

### ISSUE THREAD

**Issue by Nethmi96** [bitsoferised/ShareABook_Frontend_v.2#69]
1) Sort, filter and add pagination.
2) Display user details if the user is a registered one
3) Look into the UI

**Comment by Nethmi96** [comment]
I've add a donation as an user who is a guest to the platform.
But when receiving user details I am getting the value of `hasUser` of that particular user as **true**

![image](https://user-images.githubusercontent.com/44530828/83137781-5cae6f00-a107-11ea-8117-932011ecb645.png)

**Comment by dilinipeirs** [comment]
this error is now resolved
