### ISSUE TITLE
Error occurs when adding a 'Story Book' and 'Other' type book

### ISSUE THREAD

**Issue by Nethmi96** [bitsoferised/ShareABook_Frontend_v.2#7]
Even though i can add O/L and A/L books successfully an error is occurred when I'm trying to add a new book of category types **'Story Book**' and **'other'**.

![image](https://user-images.githubusercontent.com/44530828/79043711-701c7e00-7c1e-11ea-8760-bf2a0f8d36d3.png)

**Comment by dilinipeirs** [comment]
please check this again after you did the database filling again as i mentioned in the other issue.

This is working fine in my computer.
