### ISSUE TITLE
View user donations

### ISSUE THREAD

**Issue by Nethmi96** [bitsoferised/ShareABook_Frontend_v.2#73]
1) Display donations add by user in profile setting page
2) Design the UI

**Comment by Nethmi96** [comment]
When getting all individual user donations the following data is received from the database
![image](https://user-images.githubusercontent.com/44530828/83138786-f4608d00-a108-11ea-9552-404e87ae498a.png)

But in the api doc you've not mentioned about getting `hasUser`  filed in this situation.
Is this a mistake or should it be remain as that?
@dilinipeirs 
![image](https://user-images.githubusercontent.com/44530828/83138896-22de6800-a109-11ea-8632-4c71b3075dbe.png)

**Comment by dilinipeirs** [comment]
ah its not a mistake.. 
in the API doc i've mentioned only the fields that u need to perform the tasks. Other field(s) can also be there in the actual object
