### ISSUE TITLE
Issue in getting user details by email

### ISSUE THREAD

**Issue by Nethmi96** [bitsoferised/ShareABook_Frontend_v.2#78]
Adding donation is developed successfully and I am getting a true value boolean from the backend too. Following is a screenshot of data sent to backend and it's response.
! [image](https://user-images.githubusercontent.com/44530828/83072724-e53bf980-a08c-11ea-83b2-9d4b9d2c880a.png)

But in the admin dashboard when I am trying to display all donation, i am getting an error because the donations array sent from the back is null. I couldn't find why this is happening.
![image](https://user-images.githubusercontent.com/44530828/83072823-10bee400-a08d-11ea-8538-443d09744e1e.png)

Following is the ss of the console, but there is now error i guess 🤔 
![image](https://user-images.githubusercontent.com/44530828/83073404-06e9b080-a08e-11ea-9605-175eb0d3806a.png)

**Comment by Nethmi96** [comment]
In getting all my donations also same thing happens. I'm receiving a null array.
![image](https://user-images.githubusercontent.com/44530828/83074309-917edf80-a08f-11ea-8720-33383d0cb6c4.png)

**Comment by dilinipeirs** [comment]
this error is resolved

**Comment by Nethmi96** [comment]
I am getting an error when trying to get user details by email.
![image](https://user-images.githubusercontent.com/44530828/83137037-11e02780-a106-11ea-87d2-0ae3a40a6650.png)

There is no error in the console.
![image](https://user-images.githubusercontent.com/44530828/83137055-1c022600-a106-11ea-8e2b-383ed9102735.png)

**Comment by dilinipeirs** [comment]
there was a mistake in the URL i have provided in the doc..

here's the correct url
http://localhost:8080/shareabook/api/v1/authentication/user

i've updated doc as well
