### ISSUE TITLE
The loading spinner keeps on loading after an exception from the backend

### ISSUE THREAD

**Issue by dilinipeirs** [bitsoferised/ShareABook_Frontend_v.2#79]
While i was trying to recreate the error that was their in forgot password, the frontend went to 'loading' state and even when i pressed back it was still in that same state..

can u check whether if there's a way to put a timeout and stop the loading after sometime, *if an exception ever comes in backend*? We cannot let the users not use the site because of an error in our server ne.. 

Please do something about this

**Comment by Nethmi96** [comment]
Done
