### ISSUE TITLE
Report book/user from the product view page

### ISSUE THREAD

**Issue by dilinipeirs** [bitsoferised/ShareABook_Frontend_v.2#88]
Please add a button in the product view page as discussed, to report the particular product or the seller.

the endpoint for this task is given under 'Book Related' of the API doc

**Comment by Nethmi96** [comment]
@dilinipeirs we don't need to do this now right?

**Comment by dilinipeirs** [comment]
@Nethmi96 @RashmiChrystal let us discuss this tmoro

**Comment by dilinipeirs** [comment]
decided not to add to the MVP to be launched on 22nd sept
