### ISSUE TITLE
Misbehavior in pagination bar in My Uploads page

### ISSUE THREAD

**Issue by dilinipeirs** [bitsoferised/ShareABook_Frontend_v.2#89]
The next and previous buttons doesnt seem to work properly in the pagination bar.

please refer the video attached

[WhatsApp Video 2020-06-05 at 01.09.06.mp4.zip](https://github.com/bitsoferised/ShareABook_Frontend_v.2/files/4732380/WhatsApp.Video.2020-06-05.at.01.09.06.mp4.zip)

**Comment by Nethmi96** [comment]
solved!
