### ISSUE TITLE
Error in book edit

### ISSUE THREAD

**Issue by Nethmi96** [bitsoferised/ShareABook_Frontend_v.2#90]
When I'm trying to convert book from story book to study material I'm getting an error
![image](https://user-images.githubusercontent.com/44530828/83853959-aa446080-a733-11ea-9603-fb4d83982763.png)
![image](https://user-images.githubusercontent.com/44530828/83853996-b3353200-a733-11ea-9134-a01bf29af05b.png)

**Comment by dilinipeirs** [comment]
when i put the details as follows when converting a story book to study material, the sub category 3 field is also shown here..
why is that?

![image](https://user-images.githubusercontent.com/28673959/83963841-69c91c00-a8c6-11ea-9699-2467874aa715.png)

**Comment by dilinipeirs** [comment]
> When I'm trying to convert book from story book to study material I'm getting an error
> ![image](https://user-images.githubusercontent.com/44530828/83853959-aa446080-a733-11ea-9603-fb4d83982763.png)
> ![image](https://user-images.githubusercontent.com/44530828/83853996-b3353200-a733-11ea-9134-a01bf29af05b.png)

this error did not occur in mine. can you please recheck and tell me?

**Comment by Nethmi96** [comment]
> when i put the details as follows when converting a story book to study material, the sub category 3 field is also shown here..
> why is that?
> 
> ![image](https://user-images.githubusercontent.com/28673959/83963841-69c91c00-a8c6-11ea-9699-2467874aa715.png)

![image](https://user-images.githubusercontent.com/44530828/83963909-d2b09400-a8c6-11ea-8264-83230a4f4bfe.png)
 This error did not occur in mines ne 🙉

**Comment by Nethmi96** [comment]
> > When I'm trying to convert book from story book to study material I'm getting an error
> > ![image](https://user-images.githubusercontent.com/44530828/83853959-aa446080-a733-11ea-9603-fb4d83982763.png)
> > ![image](https://user-images.githubusercontent.com/44530828/83853996-b3353200-a733-11ea-9134-a01bf29af05b.png)
> 
> this error did not occur in mine. the book successfully got updated. can you please recheck and tell me?

Yeah it's working fine on mine too now 😕 😲

**Comment by dilinipeirs** [comment]
> > when i put the details as follows when converting a story book to study material, the sub category 3 field is also shown here..
> > why is that?
> > ![image](https://user-images.githubusercontent.com/28673959/83963841-69c91c00-a8c6-11ea-9699-2467874aa715.png)
> 
> ![image](https://user-images.githubusercontent.com/44530828/83963909-d2b09400-a8c6-11ea-8264-83230a4f4bfe.png)
> This error did not occur in mines ne 🙉

lol theres a ghost in the middle.

im closing this issue. if errors occurs further, reopen and give the status
