### ISSUE TITLE
Error in getting all admin and student details

### ISSUE THREAD

**Issue by Nethmi96** [bitsoferised/ShareABook_Frontend_v.2#93]
I am getting errors in trying to get student and admin list in the admin panel
![image](https://user-images.githubusercontent.com/44530828/83948614-f975b880-a83b-11ea-803b-d53f6be8b845.png)

Console errors are as follows:
![image](https://user-images.githubusercontent.com/44530828/83948629-0b575b80-a83c-11ea-8bdc-885f842962c1.png)
![image](https://user-images.githubusercontent.com/44530828/83948633-114d3c80-a83c-11ea-8db6-bc65facb10f4.png)

**Comment by dilinipeirs** [comment]
there was a huuuuge mistake in backend that our QA lead @Nethmee found 😫😫

users were able to register to the system more than once using the same email address which was a terrible mistake.

i corrected it and made another endpoint to check whether the email address is available to be used in the system..
check **backend issue #128** and do the necessary changes.
