### ISSUE TITLE
Error in Notifications

### ISSUE THREAD

**Issue by Nethmi96** [bitsoferised/ShareABook_Frontend_v.2#95]
I'm getting an error in notifications
![image](https://user-images.githubusercontent.com/44530828/83968957-6778b900-a8ea-11ea-9648-62553e5ab2df.png)

Console error is as belows:
![image](https://user-images.githubusercontent.com/44530828/83968967-7a8b8900-a8ea-11ea-9aa1-1dc45c52c62f.png)

**Comment by dilinipeirs** [comment]
the endpoint works from postman

![image](https://user-images.githubusercontent.com/28673959/83969390-6432fc80-a8ed-11ea-8cbc-b4c795b102bb.png)

please check from the frontend @RashmiChrystal @Nethmi96

**Comment by dilinipeirs** [comment]
![image](https://user-images.githubusercontent.com/28673959/83979101-85b1d980-a929-11ea-8415-43273f817e96.png)

error doesnt come in mine too.

but @RashmiChrystal consider these suggesstions. 
1. display the date of the notification next to the msg. then itll be good. 
2. im sending whether the notification has been read/unread by a boolean value. you can use that to indicate whether it is read/unread.
3. if you can dynamically wrap the text to be displayed in several lines without having "..." at the end, then the tooltip wont be needed as well

**And there's a bug in the notification panel**

when i click on the refresh button inside notifications, the list doubles (refer below). please remove the previous data and add the current ones or do the needful.

![image](https://user-images.githubusercontent.com/28673959/83979187-18527880-a92a-11ea-8db0-89d8938db380.png)

**Comment by dilinipeirs** [comment]
rashmi said she has completed this.
hence im closing
