### ISSUE TITLE
Error in retrieving service requests for an order id

### ISSUE THREAD

**Issue by RashmiChrystal** [bitsoferised/ShareABook_Frontend_v.2#97]
@dilinipeirs I get this is 500 error when the endpoint for retrieving the service requests for a certain order id is called. This is the endpoint,

http://localhost:8080/shareabook/api/v1/order/service-reqs

This is the error i get in the console,

![Screenshot (81)](https://user-images.githubusercontent.com/45396207/83979874-2a82e580-a92f-11ea-9d63-cda2c04f7aa2.png)

This is the error in the backend,

![Screenshot (82)](https://user-images.githubusercontent.com/45396207/83979887-3f5f7900-a92f-11ea-803c-a2c8e7c75645.png)

**Comment by dilinipeirs** [comment]
this works fine in postman
![image](https://user-images.githubusercontent.com/28673959/84006117-d8bc7880-a98b-11ea-91a9-003342b86034.png)

please provide more information..
as in what is the order id you entered, etc.

**Comment by dilinipeirs** [comment]
@RashmiChrystal as discussed,
for orders that have the status initialized -> get the cart items
else -> get the service requests.

**Comment by dilinipeirs** [comment]
@RashmiChrystal please close this issue if it is solved

**Comment by dilinipeirs** [comment]
@RashmiChrystal i am closing this issue since you have not further replied
